name: Release Linux

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Rust + target musl
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-musl

      - name: Instalar musl-tools
        run: sudo apt-get update && sudo apt-get install -y musl-tools

      - name: Compilar en modo Release
        run: cargo build --release --target x86_64-unknown-linux-musl

      - name: Renombrar binario para self_update
        run: |
          BIN_NAME="blazepilot"
          cp "target/x86_64-unknown-linux-musl/release/$BIN_NAME" "./${BIN_NAME}-x86_64-unknown-linux-musl"

      - name: Subir binario al Release
        uses: softprops/action-gh-release@v2
        with:
          files: blazepilot-x86_64-unknown-linux-musl
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}